# Generated by Django 4.2.3 on 2023-07-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('category', models.CharField(choices=[('SP', 'Спорт'), ('POL', 'Политика'), ('ECO', 'Экономика'), ('SOC', 'Общество')], default='SOC', max_length=3, verbose_name='Категория')),
                ('status', models.BooleanField(default=True, verbose_name='Статус публикации')),
                ('cover', models.ImageField(blank=True, default='image.jpg', upload_to='uploads/posts', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
